# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: aranda
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: app-jogajunto
# "service" is the name of this project. This will also be added to your AWS resource names.
service: app-jogajunto

provider:
  name: aws
  runtime: python3.12
  region: sa-east-1
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:Query
          Resource:
            - "arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/lobbies"
            - "arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/lobbies/index/*"
  timeout: 5
  httpApi:
    metrics: true

functions:
  create_lobby:
    handler: src.handlers.create_lobby.handler
    events:
      - httpApi:
          path: /lobbies
          method: post
  get_lobby:
    handler: src.handlers.get_lobby.handler
    events:
      - httpApi:
          path: /lobbies/{lobby_id}
          method: get
  join_lobby:
    handler: src.handlers.join_lobby.handler
    events:
      - httpApi:
          path: /lobbies/{lobby_id}/join
          method: post

resources:
  Resources:
    LobbiesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: lobbies
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: GSI1_PK
            AttributeType: S
          - AttributeName: GSI1_SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE 
        GlobalSecondaryIndexes:
          - IndexName: GSI1
            KeySchema:
              - AttributeName: GSI1_PK
                KeyType: HASH
              - AttributeName: GSI1_SK
                KeyType: RANGE
            Projection:
              ProjectionType: ALL  
        